name: Linting

on:
  - pull_request


jobs:
  pylint_py3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ricardochaves/python-lint@v1.3.0
        with:
          python-root-list: "corona_rki_prometheus_exporter"
          use-pylint: true
          use-pycodestyle: false
          use-flake8: true
          use-black: true
          use-mypy: true
          use-isort: false
          extra-pylint-options: ""
          extra-pycodestyle-options: ""
          extra-flake8-options: "--max-line-length=200 --ignore=E203,W503"
          extra-black-options: "--line-length 200"
          extra-mypy-options: ""
          extra-isort-options: ""
